// ADMIN
export const ADD_CLASS_START = "ADD_CLASS_START"
export const ADD_CLASS_SUCCESS = "ADD_CLASS_SUCCESS"
export const ADD_CLASS_FAILURE = "ADD_CLASS_FAILURE"
export const DELETE_EVENT_SUCCESS = "DELETE_EVENT_SUCCESS"
export const DELETE_EVENT_START = "DELETE_EVENT_START"
export const DELETE_EVENT_FAILURE = "DELETE_EVENT_FAILURE"
export const LOAD_CLASSES = "LOAD_CLASSES"
export const LOAD_EVENTS = "LOAD_EVENTS"
export const SCHEDULE_EVENT = "SCHEDULE_EVENT"
export const SCHEDULE_EVENT_START = "SCHEDULE_EVENT_START"
export const SCHEDULE_EVENT_SUCCESS = "SCHEDULE_EVENT_SUCCESS"
export const SCHEDULE_EVENT_FAILURE = "SCHEDULE_EVENT_FAILURE"

// add new user
export const REGISTER_USER_START = "REGISTER_USER_START"
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS"
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE"

// login/logout
export const LOGIN_START = "LOGIN_START"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"
export const AUTHENTICATION_FAILURE = "AUTHENTICATION_FAILURE"
export const LOGOUT_USER = "LOGOUT_USER"

// load class
export const LOAD_CLASSES_START = "LOAD_CLASSES_START"
export const LOAD_CLASSES_SUCCESS = "LOAD_CLASSES_SUCCESS"
export const LOAD_CLASSES_FAILURE = "LOAD_CLASSES_FAILURE"

// load events
export const LOAD_EVENTS_START = "LOAD_EVENTS_START"
export const LOAD_EVENTS_SUCCESS = "LOAD_EVENTS_SUCCESS"
export const LOAD_EVENTS_FAILURE = "LOAD_EVENTS_FAILURE"

// request class
export const REQUEST_CLASS_START = "REQUEST_CLASS_START"
export const REQUEST_CLASS_SUCCESS = "REQUEST_CLASS_SUCCESS"
export const REQUEST_CLASS_FAILURE = "REQUEST_CLASS_FAILURE"

// save user
export const SAVE_USER_START = "SAVE_USER_START"
export const SAVE_USER_SUCCESS = "SAVE_USER_SUCCESS"
export const SAVE_USER_FAILURE = "SAVE_USER_FAILURE"

export const SUBMIT_FEEDBACK_FAILURE = "SUBMIT_FEEDBACK_FAILURE"
export const SUBMIT_FEEDBACK_START = "SUBMIT_FEEDBACK_START"
export const SUBMIT_FEEDBACK_SUCCESS = "SUBMIT_FEEDBACK_SUCCESS"

// validate username
export const VALIDATE_USERNAME_START = "VALIDATE_USERNAME_START"
export const VALIDATE_USERNAME_SUCCESS = "VALIDATE_USERNAME_SUCCESS"
export const VALIDATE_USERNAME_FAILURE = "VALIDATE_USERNAME_FAILURE"

// middleware actions
export const API = "API"
export const API_START = "API_START"
export const API_END = "API_END"
export const ACCESS_DENIED = "ACCESS_DENIED"
export const API_ERROR = "API_ERROR"

// misc
export const SET_LOCAL_USER = "SET_LOCAL_USER"
